[package]
name = "imgreduce"
version = "0.1.0"
authors = ["Johan Larsson <johan.larsson1989@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.8"
clap = "2.33.3"
regex = "1"